### ISSUE TITLE
raw-loader 2.0 not working with pug-html-loader

### ISSUE THREAD

**Issue by nstuyvesant** [webpack-contrib/raw-loader#71]
* Operating System: macOS 10.14.3
* Node Version: 10.15.2
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* raw-loader Version: 2.0.0
* pug-html-loader Version: 1.1.5

### Expected Behavior
This part of my webpack config (module.rules) will work with raw-loader 2.0.0 the same way it worked with raw-loader 1.0.0:
```js
        {
          test: /\.pug$/,
          use: ['raw-loader', 'pug-html-loader']
        }
```

### Actual Behavior
Pug templates were not loaded.

### Code

```js
        {
          test: /\.pug$/,
          use: ['raw-loader', 'pug-html-loader']
        }
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?
Use the pug-html-loader 1.1.5 with a small website that uses pug templates (such as a default site built using generator-angular-fullstack (yeoman).

[Link to my webpack config](https://github.com/nstuyvesant/shy/blob/master/webpack.make.js#L55)

**Comment by evilebottnawi** [comment]
It is breaking change please read https://github.com/webpack-contrib/raw-loader/releases/tag/v2.0.0, you need rewrite code, you can provide example of code and I'll show you how to do it right

**Comment by birtles** [comment]
> you can provide example of code and I'll show you how to do it right

I'm not sure if this is the same issue but I am having trouble with 2.0 and `ExtractTextPlugin`: [webpack config](https://github.com/birtles/10sai/blob/dev/webpack.common.js#L24-L35), [usage example](https://github.com/birtles/10sai/blob/dev/src/index.tsx#L24).

I get `TypeError: text.forEach is not a function`. [Error stack here](https://circleci.com/gh/birtles/10sai/183).

Any help with rewriting this would be much appreciated.

**Comment by evilebottnawi** [comment]
`ExtractTextPlugin` is deprecated and no longer support and doesn't support ES syntax, you can fork this plugin and fix problem or you can create own plugin for extracting pug templates. Alternative https://github.com/peerigon/extract-loader

**Comment by birtles** [comment]
Great, thank you so much. I'll give `extract-loader` another try.

**Comment by brenc** [comment]
Upgrading to 2.0 broke loading Knockout components. This was a simple fix but I had to dig for it.

For future reference, here is my old code that worked with `raw-loader@1`:

```
    ko.components.register('user-list', {
      viewModel: { instance: userListVm },
      template: require('./components/user-list.html')
    })
```
Here is what works with `raw-loader@2`:
```
    // Top of the file
    import UserListT from './components/user-list.html'

    ko.components.register('user-list', {
      viewModel: { instance: userListVm },
      template: UserListT
    })
```

**Comment by evilebottnawi** [comment]
@brenc can you create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
Yep, raw-loader use `ES` modules, so you need update code, rewrite all on `import`

**Comment by evilebottnawi** [comment]
Also you can use `require.default`

**Comment by nstuyvesant** [comment]
Closing as this was a breaking change. Switching to html-loader allowed me to minimize syntax changes to my webpack config.
